# Generated by Django 4.0.1 on 2022-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Tytuł")),
                ("author", models.CharField(max_length=256, verbose_name="Autor")),
                ("date_of_puclication", models.DateField(verbose_name="Data publikacji")),
                ("isbn", models.BigIntegerField(verbose_name="ISBN")),
                ("pages", models.IntegerField(verbose_name="Liczba stron")),
                ("cover", models.ImageField(upload_to="covers/", verbose_name="Okładka")),
                ("lang", models.CharField(max_length=32, verbose_name="Język publikacji")),
            ],
        ),
    ]
