# Generated by Django 4.0.1 on 2022-01-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="date_of_puclication",
            new_name="date_of_publication",
        ),
    ]
