# Generated by Django 4.0.1 on 2022-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_book_cover_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(null=True, verbose_name='Data publikacji'),
        ),
    ]
